service: ms-boilerplate

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  profile: pastiti

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'